def exceptionHandling():
  try:
     a="data"
     b=20
     c=0
     d=(a+b)/c
     print(d)
  except:
      print("in the except block") 
exceptionHandling()