def exceptionHandling():
  try:
     value="data"
     num=20
     num1=0
     division=(value+num)/num1
     print(division)
  except:
      print("in the except block") 
exceptionHandling()
